# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20170701_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='like',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='view',
            new_name='views',
        ),
    ]
